version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: exam_planning_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: exam_planning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: exam_planning_backend
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/exam_planning
      - SECRET_KEY=your_secret_key_here
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your_email@example.com
      - MAIL_PASSWORD=your_email_password
      - MAIL_USE_TLS=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
